import "./globals.css";
import { Metadata } from "next";
import RootClient from "./RootClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootClient>{children}</RootClient> {/* Wrapping with RootClient */}
      </body>
    </html>
  );
}
